n = int(input('Digite um numero: '))
print(f'A tabuada do numero {n} é:')
print(12*'_')
print(f'{n} X  1 = {n*1}')
print(f'{n} X  2 = {n*2}')
print(f'{n} X  3 = {n*3}')
print(f'{n} X  4 = {n*4}')
print(f'{n} X  5 = {n*5}')
print(f'{n} X  6 = {n*6}')
print(f'{n} X  7 = {n*7}')
print(f'{n} X  8 = {n*8}')
print(f'{n} X  9 = {n*9}')
print(f'{n} X 10 = {n*10}')
print(12*'_')
